[package]
name = "random_uint256"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
uint = { package = "uint", version = "0.9.5", features = ["std", "arbitrary"] }

